FROM repo.docker.com/dotnet/aspnet:6.0-curl AS base
ENV TZ=Asia/Tehran 
ENV ASPNETCORE_ENVIRONMENT=Alpha
WORKDIR /app

FROM repo.docker.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY . .
WORKDIR "ApiGateway/"
RUN dotnet restore "ApiGateway.csproj"
RUN dotnet build "ApiGateway.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ApiGateway.csproj" -c Release -o /app/publish /p:UseAppHost=false

EXPOSE 5000

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
EXPOSE 5000
ENTRYPOINT ["dotnet", "ApiGateway.dll"]